version: "3.9"
   
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
    devices: 
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip1:/dev/gpiochip1"
      - "/dev/gpiomem:/dev/gpiomem"
    env_file:
      - .env
    image: app:water_world
    container_name: water_world_app
    command: python main.py
    restart: unless-stopped

  django:
    build:
      context: ./django
    volumes:
      - ./django:/django
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    image: django:water_world_gunicorn
    container_name: water_world_gunicorn_server
    entrypoint: /django/entrypoint.sh
    restart: unless-stopped
  
  mqtt:
    build:
      context: ./mosquitto
    user: ${UID}:${GID}
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    env_file:
      - .env
    image: mqtt:water_world_server
    container_name: water_world_mqtt_server
    restart: unless-stopped

  web:
    build:
      context: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django
    image: nginx:water_world_web_server
    container_name: water_world_nginx_server
    restart: unless-stopped

volumes:
  static:
    
