# Generated by Django 4.0.4 on 2022-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_system', models.BooleanField(verbose_name='System on/off switch')),
                ('system_mode', models.IntegerField(choices=[(1, 'Sensor Mode'), (2, 'Timer Mode')])),
                ('seconds_to_pump', models.FloatField(verbose_name='Liters pumped per pump activation')),
                ('sensor_read_interval_hours', models.FloatField(verbose_name='Sensor read interval in sensor mode (hours)')),
                ('watering_interval_hours', models.FloatField(verbose_name='Watering interval in timer mode (hours)')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Event message')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event type')),
                ('event_time', models.DateTimeField(verbose_name='Event timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='WaterPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_activated', models.DateTimeField(blank=True, null=True, verbose_name='Pump activation timestamp')),
                ('pump_stopped', models.DateTimeField(blank=True, null=True, verbose_name='Pump stopping timestamp')),
            ],
        ),
    ]
