# Generated by Django 4.0.3 on 2022-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_system', models.BooleanField(verbose_name='System on/off switch')),
                ('liters_to_pump', models.FloatField(verbose_name='Liters pumped per pump activation')),
                ('sensor_read_interval_hours', models.IntegerField(verbose_name='Sensor read interval in hours')),
            ],
        ),
        migrations.CreateModel(
            name='WaterPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_activated', models.DateTimeField(blank=True, null=True, verbose_name='Pump activation timestamp')),
                ('pump_stopped', models.DateTimeField(blank=True, null=True, verbose_name='Pump stopping timestamp')),
            ],
        ),
    ]
