# Generated by Django 4.0.3 on 2022-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Event message')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event type')),
                ('event_time', models.DateTimeField(verbose_name='When the event happened')),
            ],
        ),
    ]
