# Generated by Django 4.0.4 on 2022-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_world', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterpump',
            options={'verbose_name_plural': 'Pump activations'},
        ),
        migrations.AlterField(
            model_name='config',
            name='enable_system',
            field=models.BooleanField(verbose_name='System ON'),
        ),
        migrations.AlterField(
            model_name='config',
            name='seconds_to_pump',
            field=models.FloatField(verbose_name='Seconds pumped per pump activation'),
        ),
    ]
